---
- name: Install apache and related packages
  apt:
    name: "{{ item }}"
    state: present
  tags: apache
  with_items:
    - apache2

- name: Add mod_rewrite configuration
  copy: src=rewrite.conf dest=/etc/apache2/mods-available/rewrite.conf force=no

- name: Enable apache modules
  apache2_module: state=present name={{ item }}
  with_items: apache_modules

- name: Generate self-signed certificate
  command: openssl req -new -nodes -x509 -subj "{{ apache_ssl.cert.subj }}" -days 3650 -keyout /etc/ssl/private/{{ apache_ssl.key.file }} -out /etc/ssl/private/{{ apache_ssl.cert.file }}
  when: apache_ssl.key.data is undefined
  no_log: True

- name: Install ssl key
  copy:
    content: "{{ apache_ssl.key.data }}"
    dest: /etc/ssl/private/{{ apache_ssl.key.file }}
    mode: 0640
  when: apache_ssl.key.data is defined
  no_log: True

- name: Install ssl cert
  copy:
    content: "{{ apache_ssl.cert.data }}"
    dest: /etc/ssl/private/{{ apache_ssl.cert.file }}
    mode: 0640
  when: apache_ssl.cert.data is defined
  no_log: True

- name: Install ssl certificate chain
  copy:
    content: "{{ apache_ssl.chain.data }}"
    dest: /etc/ssl/private/{{ apache_ssl.chain.file }}
    mode: 0640
  when: apache_ssl.chain.data is defined
  no_log: True

- file: path=/srv              state=directory owner=www-data group=staff mode=2775
- file: path=/srv/sites        state=directory owner=www-data group=staff mode=2775
- file: path=/srv/sites/master state=directory
- file: path=/etc/apache2/sites-enabled/conf.d state=directory

# note that ansible 'copy' copies from the control machine to the host:
# - copy: src=/var/www/html/index.html dest=/srv/sites/master/index.html force=no
- name: Copy over default index.html
  shell: cp /var/www/html/index.html /srv/sites/master/index.html
  args:
    creates: /srv/sites/master/index.html

- name: Update permissions on sites directory
  file: dest=/srv/sites owner=www-data group=staff mode="g+rw" recurse=yes

- name: Update default configuration
  template:
    src: 000-default.conf.j2
    dest: /etc/apache2/sites-available/000-default.conf
    owner: root
    group: root
    mode: 0644

- name: Update websites configuration
  copy:
    content: "{{ item.data }}"
    dest: /etc/apache2/sites-enabled/conf.d/{{ item.file }}
    mode: 0644
  with_items: apache_sites
  when: apache_sites is defined
  no_log: True

- service: name=apache2 state=restarted

- name: Configure the firewall (http)
  ufw: rule=allow port={{ item }}
  with_items:
    - http
    - https
...
